/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HubCompassMap {
        /**
          * Optional [longitude, latitude] map center
         */
        "center": [number, number];
        /**
          * Optional array of datasets to add to map
         */
        "datasetIds": string[];
        /**
          * Optional Map id to display
         */
        "mapId": string;
        /**
          * Optional location to calculate service center. Changing this will update the point
         */
        "serviceAreaPoint": any;
        /**
          * Option to show search input
         */
        "showSearch": boolean;
        /**
          * Optional travel mode: walking, etc.  TODO fix travel mode type and values
         */
        "travelMode": any;
        /**
          * Optional map zoom level
         */
        "zoom": number;
    }
}
declare global {
    interface HTMLHubCompassMapElement extends Components.HubCompassMap, HTMLStencilElement {
    }
    var HTMLHubCompassMapElement: {
        prototype: HTMLHubCompassMapElement;
        new (): HTMLHubCompassMapElement;
    };
    interface HTMLElementTagNameMap {
        "hub-compass-map": HTMLHubCompassMapElement;
    }
}
declare namespace LocalJSX {
    interface HubCompassMap {
        /**
          * Optional [longitude, latitude] map center
         */
        "center"?: [number, number];
        /**
          * Optional array of datasets to add to map
         */
        "datasetIds"?: string[];
        /**
          * Optional Map id to display
         */
        "mapId"?: string;
        /**
          * Optional location to calculate service center. Changing this will update the point
         */
        "serviceAreaPoint"?: any;
        /**
          * Option to show search input
         */
        "showSearch"?: boolean;
        /**
          * Optional travel mode: walking, etc.  TODO fix travel mode type and values
         */
        "travelMode"?: any;
        /**
          * Optional map zoom level
         */
        "zoom"?: number;
    }
    interface IntrinsicElements {
        "hub-compass-map": HubCompassMap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hub-compass-map": LocalJSX.HubCompassMap & JSXBase.HTMLAttributes<HTMLHubCompassMapElement>;
        }
    }
}
